export const GET_BACKUPS = "GET_BACKUPS";
export const CREATE_BACKUP_SUCCESS = "CREATE_BACKUP_SUCCESS";
export const CREATE_BACKUP_ERROR = "CREATE_BACKUP_ERROR";
export const DELETE_BACKUP_SUCCESS = "DELETE_BACKUP_SUCCESS";
export const DELETE_BACKUP_ERROR = "DELETE_BACKUP_ERROR";
export const RESTORE_SUCCESS = "RESTORE_SUCCESS";
export const RESTORE_ERROR = "RESTORE_ERROR";